-- Quota Platform: initial schema (PostgreSQL)

CREATE TABLE plans (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          VARCHAR(20)    NOT NULL,
    monthly_limit INTEGER        NOT NULL,
    monthly_price NUMERIC(10, 2) NOT NULL,
    description   VARCHAR(255),
    CONSTRAINT uk_plans_type UNIQUE (type),
    CONSTRAINT ck_plans_limit CHECK (monthly_limit >= 0)
);

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  VARCHAR(120) NOT NULL,
    email      VARCHAR(180) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    plan_id    BIGINT      NOT NULL,
    status     VARCHAR(20) NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_subscriptions_user UNIQUE (user_id),
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES plans (id),
    CONSTRAINT ck_subscriptions_status CHECK (status IN ('ACTIVE', 'EXPIRED'))
);

CREATE TABLE usage_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT       NOT NULL,
    operation       VARCHAR(120) NOT NULL,
    quota_used      INTEGER      NOT NULL,
    usage_period    VARCHAR(7)   NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_usage_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE CASCADE,
    CONSTRAINT ck_usage_quota CHECK (quota_used > 0)
);

CREATE INDEX idx_usage_sub_period ON usage_logs (subscription_id, usage_period);
